mongodb.connection.url=${MONGODB_CONECTION_URL:mongodb://root:example@localhost:27017}
logging.file.name=myapp.log
logging.level.ro.unibuc.hello=DEBUG

# Metrics related properties
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=info,health,prometheus
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Enable server request timing - useful for more detailed metrics
server.tomcat.mbeanregistry.enabled=true

# Port standard (dacă e necesar)
server.port=8080
