groups:
  - name: AppAlerts
    rules:
      - alert: WARNING-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 10
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 50
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Instance is down"
          description: "The monitored instance is not responding"

      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0.00001  # modificare
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "High rate of 5xx errors"
          description: "More than 0.001% of requests are failing with 5xx errors"

