pipeline {
    agent any

    tools {
        jdk 'jdk21'
    }

    environment {
        DOCKER_CREDENTIALS = credentials("docker_password") // aici username:password
        GITHUB_TOKEN = credentials("github_token")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Docker Login') {
            steps {
                script {
                    def username = DOCKER_CREDENTIALS_USR // Accesarea username-ului
                    def password = DOCKER_CREDENTIALS_PSW // Accesarea parolei

                    sh """
                        echo "${password}" | docker login -u "${username}" --password-stdin
                    """

                    env.DOCKER_USERNAME = username
                }
            }
        }

        stage('Tag image') {
            steps {
                script {
                    sh('git fetch --tags')
                    def major = sh(script: "git tag | sort --version-sort | tail -1 | cut -d . -f 1", returnStdout: true).trim()
                    def minor = sh(script: "git tag | sort --version-sort | tail -1 | cut -d . -f 2", returnStdout: true).trim()
                    def patch = sh(script: "git tag | sort --version-sort | tail -1 | cut -d . -f 3", returnStdout: true).trim()

                    def minorNext = (minor as Integer) + 1

                    env.MAJOR_VERSION = major
                    env.MINOR_VERSION = minorNext.toString()
                    env.PATCH_VERSION = patch
                    env.IMAGE_TAG = "${major}.${minorNext}.${patch}"
                }
                sh "docker build -t ${DOCKER_USERNAME}/hello-img:${IMAGE_TAG} ."
                sh "docker push ${DOCKER_USERNAME}/hello-img:${IMAGE_TAG}"

                sh "git tag ${env.IMAGE_TAG}"
                sh "git push https://$GITHUB_TOKEN@github.com/PartyPeeps/service.git ${env.IMAGE_TAG}"
            }
        }



        stage('Test') {
            steps {
                sh "IMAGE_TAG=${env.IMAGE_TAG} docker compose up -d hello mongo"
            }
        }
    }
}
